/** Khmer UI copy for Math Tug of War. Digits and math symbols stay Western. */
export const km = {
  newMatch: "ប្រកួតថ្មី",
  playAgain: "លេងម្តងទៀត",
  grade: "ថ្នាក់ទី",
  gradeLevel: "កម្រិតថ្នាក់",
  gradeLocked: "បញ្ចប់ ឬកំណត់ប្រកួតឡើងវិញ មុនប្តូរថ្នាក់",
  blue: "ខៀវ",
  red: "ក្រហម",
  blueWins: "ខៀវឈ្នះ!",
  redWins: "ក្រហមឈ្នះ!",
  blueArrow: "ខៀវ ←",
  redArrow: "→ ក្រហម",
  bluePanel: "បន្ទះខៀវ",
  redPanel: "បន្ទះក្រហម",
  toggleSign: "ប្តូរសញ្ញាអវិជ្ជមាន",
  backspace: "លុប",
  submitAnswer: "បញ្ចូលចម្លើយ",
  blueAlt: "អ្នកលេងខៀវកំពុងទាញព្រ័ត្រ",
  redAlt: "អ្នកលេងក្រហមកំពុងទាញព្រ័ត្រ",
  hint: "ឆ្លើយឱ្យបានត្រឹមត្រូវដើម្បីទាញព្រ័ត្រ។ អ្នកទាញសញ្ញាសម្គាល់មកដល់ខាងខ្លួនបានមុន គឺជាអ្នកឈ្នះ។",
  metaTitle: "ល្បែងទាញព្រ័ត្រគណិតវិទ្យា",
  metaTitleFull: "ល្បែងទាញព្រ័ត្រគណិតវិទ្យា — ល្បែងគណិត ២ នាក់",
  metaDescription:
    "ល្បែងទាញព្រ័ត្រគណិតវិទ្យា ២ នាក់។ ដោះស្រាយប្រមាណវិធី ដើម្បីទាញព្រ័ត្រមកខាងខ្លួន ហើយឈ្នះ។",
  pageNotFound: "រកមិនឃើញទំព័រ",
  pageNotFoundBody: "ទំព័រដែលអ្នកកំពុងស្វែងរកមិនមាន ឬត្រូវបានផ្លាស់ប្ដូរ។",
  goHome: "ត្រលប់ទៅទំព័រដើម",
  pageLoadFailed: "ទំព័រនេះបរាជ័យក្នុងការផ្ទុកឡើងវិញ។",
  pageLoadFailedBody:
    "មានបញ្ហា! សូមព្យាយាមផ្ទុកឡើងវិញ ឬត្រលប់ទៅទំព័រដើម។",
  tryAgain: "ព្យាយាមម្តងទៀត",
} as const;
