/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiRoomRoomIdRouteImport } from './routes/api/room.$roomId'
import { Route as ApiRoomCreateRouteImport } from './routes/api/room.create'
import { Route as CRoomIdClaimTokenRouteImport } from './routes/c.$roomId.$claimToken'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRoomRoomIdRoute = ApiRoomRoomIdRouteImport.update({
  id: '/api/room/$roomId',
  path: '/api/room/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRoomCreateRoute = ApiRoomCreateRouteImport.update({
  id: '/api/room/create',
  path: '/api/room/create',
  getParentRoute: () => rootRouteImport,
} as any)
const CRoomIdClaimTokenRoute = CRoomIdClaimTokenRouteImport.update({
  id: '/c/$roomId/$claimToken',
  path: '/c/$roomId/$claimToken',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/room/$roomId': typeof ApiRoomRoomIdRoute
  '/api/room/create': typeof ApiRoomCreateRoute
  '/c/$roomId/$claimToken': typeof CRoomIdClaimTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/room/$roomId': typeof ApiRoomRoomIdRoute
  '/api/room/create': typeof ApiRoomCreateRoute
  '/c/$roomId/$claimToken': typeof CRoomIdClaimTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/room/$roomId': typeof ApiRoomRoomIdRoute
  '/api/room/create': typeof ApiRoomCreateRoute
  '/c/$roomId/$claimToken': typeof CRoomIdClaimTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/api/room/$roomId' | '/api/room/create' | '/c/$roomId/$claimToken'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/room/$roomId' | '/api/room/create' | '/c/$roomId/$claimToken'
  id:
    | '__root__'
    | '/'
    | '/api/room/$roomId'
    | '/api/room/create'
    | '/c/$roomId/$claimToken'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiRoomRoomIdRoute: typeof ApiRoomRoomIdRoute
  ApiRoomCreateRoute: typeof ApiRoomCreateRoute
  CRoomIdClaimTokenRoute: typeof CRoomIdClaimTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/room/$roomId': {
      id: '/api/room/$roomId'
      path: '/api/room/$roomId'
      fullPath: '/api/room/$roomId'
      preLoaderRoute: typeof ApiRoomRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/room/create': {
      id: '/api/room/create'
      path: '/api/room/create'
      fullPath: '/api/room/create'
      preLoaderRoute: typeof ApiRoomCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$roomId/$claimToken': {
      id: '/c/$roomId/$claimToken'
      path: '/c/$roomId/$claimToken'
      fullPath: '/c/$roomId/$claimToken'
      preLoaderRoute: typeof CRoomIdClaimTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiRoomRoomIdRoute: ApiRoomRoomIdRoute,
  ApiRoomCreateRoute: ApiRoomCreateRoute,
  CRoomIdClaimTokenRoute: CRoomIdClaimTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
